version: "3.9"
services:
  node-app:
    build: .
    container_name: node-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo-db
    environment:
      - MONGO_URL=mongodb://admin:password@mongo-db:27017
    networks:
      - app-network

  mongo-db:
    image: mongo:6.0
    container_name: mongo-db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - app-network

  mongo-express:
    image: mongo-express:1.0
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongo-db
    depends_on:
      - mongo-db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
